### ISSUE TITLE
Setting Bizcat as Linux TTY console font

### ISSUE THREAD

**Issue by lowercasename** [robey/font-problems#4]
Hi, and thank you for these amazing fonts (and, from my teenage self, for Eggdrop!) I’m trying to get Bizcat working in my Linux TTY console on a Raspberry Pi Zero W, but when I run `setfont bizcat.psf`, I get an error message (`Font position 32 is nonblank, background will look funny`), and indeed it does! The background is made up of dashes instead of empty spaces. Am I doing something wrong?

**Comment by robey** [comment]
crap, now it's doing that for me too! ... i messed something up. :)

**Comment by robey** [comment]
i think i got it: linux really wants glyphs 0x20 - 0x7f to be mapped to ascii, even if there's an attached map that says otherwise. i knew that!

but recently i changed the mapfile to omit a bunch of unused glyphs in that first 0x20 range. adding them back, mapped into nothing, seems to have made setfont stop complaining.

i posted a new psf to github -- does that one work for you?

**Comment by lowercasename** [comment]
You tell me!

![bizcat](https://user-images.githubusercontent.com/1748384/83966156-704c9900-a8b0-11ea-8a91-0037b9545e26.png)

**Comment by robey** [comment]
yayyyyyy!
